<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>ae208613-b778-4beb-bdf1-c87bc5a96ca9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Twitter&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Twitter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2e83208c-272e-4eee-963e-d25b8b165046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Twitter</value>
      <webElementGuid>729ed2ea-7e57-48c5-8f99-31ac4729e846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/footer-twitter.svg</value>
      <webElementGuid>f1fcf18b-6835-4cf7-94d6-357cc5148fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>4a00d557-a922-4ad9-ab19-bcfc2dfa2be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fixed</value>
      <webElementGuid>b039f7d0-9ff8-4ed1-b265-99bf44b73a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/images/footer-twitter.svg 1x, /images/footer-twitter.svg 2x</value>
      <webElementGuid>6488fff0-0fb4-4d43-883d-18a0c71e68eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-70ca4w&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg css-ljahw8&quot;]/div[@class=&quot;css-j5tk71&quot;]/div[@class=&quot;css-1u1l5yw&quot;]/div[@class=&quot;MuiBox-root css-1ay9vb9&quot;]/a[1]/span[1]/img[1]</value>
      <webElementGuid>2c7bf03f-1c73-4ff2-abe5-5df14ee54c0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[12]/div/div[2]/div/div/a/span/img</value>
      <webElementGuid>810c7364-1a5c-4f45-b8eb-346bc784cc7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Twitter']</value>
      <webElementGuid>25e05e6c-a946-452b-8da0-a01cdb0d8ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span/img</value>
      <webElementGuid>062a6a78-a88b-420e-a05f-3c02b8649c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Twitter' and @src = '/images/footer-twitter.svg']</value>
      <webElementGuid>ba1d0bf4-76ca-4cf8-a9f3-c12b2e335f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div[2]/span/img</value>
      <webElementGuid>db807e07-21d3-4af0-a89c-d16fb93ef862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Scroll down']</value>
      <webElementGuid>951e79e2-0a42-4f21-bb1d-965c64673579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span/img</value>
      <webElementGuid>492cc88f-b8a8-4d12-bcbc-ea250d985539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Scroll down' and @src = '/images/scroll-down-hero.svg']</value>
      <webElementGuid>3bebba01-348f-4fbb-af15-69d39919f092</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
